cp -r /Users/zhaoxuxu/expensify/react-native-live-markdown/LICENSE ./
cp -r /Users/zhaoxuxu/expensify/react-native-live-markdown/README.md ./
cp -r /Users/zhaoxuxu/expensify/react-native-live-markdown/RNLiveMarkdown.podspec ./
cp -r /Users/zhaoxuxu/expensify/react-native-live-markdown/android ./
cp -r /Users/zhaoxuxu/expensify/react-native-live-markdown/cpp ./
cp -r /Users/zhaoxuxu/expensify/react-native-live-markdown/ios ./
cp -r /Users/zhaoxuxu/expensify/react-native-live-markdown/lib ./
cp -r /Users/zhaoxuxu/expensify/react-native-live-markdown/package.json ./
cp -r /Users/zhaoxuxu/expensify/react-native-live-markdown/parser ./
cp -r /Users/zhaoxuxu/expensify/react-native-live-markdown/react-native.config.js ./
cp -r /Users/zhaoxuxu/expensify/react-native-live-markdown/src ./
